# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\xxmrg\Documents\2 курс (ИТ-22б)\Языки программирования\ЛР2\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 578)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(40, 50, 290, 450))
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 530, 93, 28))
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "background-color: rgb(255,100,0);\n"
                                      "color: white;\n"
                                      "width: 75px;\n"
                                      "height: 75px;\n"
                                      "font-size: 14px;\n"
                                      "font-weight: bold;\n"
                                      "\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 530, 93, 28))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "background-color: rgb(0,255,0);\n"
                                        "color: black;\n"
                                        "width: 75px;\n"
                                        "height: 75px;\n"
                                        "font-size: 14px;\n"
                                        "font-weight: bold;\n"
                                        "\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 530, 93, 28))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
                                        "background-color: rgb(255,0,0);\n"
                                        "color: white;\n"
                                        "width: 75px;\n"
                                        "height: 75px;\n"
                                        "font-size: 14px;\n"
                                        "font-weight: bold;\n"
                                        "\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 10, 93, 28))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
                                        "background-color: rgb(255,0,0);\n"
                                        "color: white;\n"
                                        "font-weight: bold;\n"
                                        "\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Shuffle"))
        self.pushButton_2.setText(_translate("Form", "Play"))
        self.pushButton_3.setText(_translate("Form", "Stop"))
        self.pushButton_4.setText(_translate("Form", "ON"))

